### PR TITLE
fix: resolve previewed document URL any language

### PR DESCRIPTION
**Pull request by AriFreyr**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Preview only works for the default language, fetch the preview document for all languages. Otherweise getByID will crash before calling the linkResolver

## Checklist:

- [ ] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by angeloashmore** [comment]
Hi @AriFreyr, thanks for the PR!

This is a good catch. I wonder if this could cause problems in other parts of an app once it gets past `getByID()`. If you preview a document in language "B", for example, but the rest of app uses language "A", you may be mixing documents from other languages.

I can see how your change is necessary, even in that situation. If an app uses the URL to determine how the client is configured, for example, you would need to first get past `resolvePreviewURL()` for the document.

## Requested changes

Could you update the tests for `resolvePreviewURL()` in `test/client-resolvePreviewURL.test.ts`?

In each test, the following `lang: "*"` line should be added in the `createMockQueryHandler()` function:

```diff
  server.use(
    createMockRepositoryHandler(t),
    createMockQueryHandler(t, [queryResponse], undefined, {
      ref: previewToken,
      q: `[[at(document.id, "${documentId}")]]`,
+     lang: "*",
    }),
  );
```

I can also make these changes if you enable maintainer edits ([details here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)).

Thanks!

**Comment by AriFreyr** [comment]
> This is a good catch. I wonder if this could cause problems in other parts of an app once it gets past `getByID()`. If you preview a document in language "B", for example, but the rest of app uses language "A", you may be mixing documents from other languages.

Yeah i can see how it would be confusing, i think the only other way to address this (and maybe a better way, atleast for my use case) would be if the preview callback url provided the language as query param,

I fixed the tests, should be working now

**Comment by angeloashmore** [comment]
Great! Thanks for updating the tests. I'll merge and publish this. 🙂

> I think the only other way to address this (and maybe a better way, atleast for my use case) would be if the preview callback url provided the language of the document as a query param.

I could see that being useful. Since the previewed document contains the language in the `lang` parameter, the language should be obtainable easily, albeit with a network request.

**Comment by angeloashmore** [comment]
This has been published in `v6.1.0`.

Thanks again @AriFreyr!

**Pull request merged**
