### PR TITLE
refactor: rename features and update documentation references

### PR DESCRIPTION
**Pull request by lihbr**
## Types of changes

- [x] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR does two things.
1. It reflects the new name of the renamed features on the product and deprecate old features names
2. It update all documentation references

#### Public

- `HTMLFunctionSerializer` (deprecated) is now HTMLRichTextFunctionSerializer
- `HTMLMapSerializer` (deprecated) is now HTMLRichTextMapSerializer

#### Internal

- `createDefaultHTMLSerializer` is now `createDefaultHTMLRichTextSerializer`
- `HTMLMapSerializerFunction` is now `HTMLRichTextMapSerializerFunction`

#### Public

- `predicate` (deprecated) is now `filter`
- `predicates` params (deprecated) is now `filters` param

#### Internal

- `appendPredicates` is now `appendFilters`
- `everyTagPredicate` is now `everyTagFilter`
- `someTagsPredicate` is now `someTagsFilter`
- `typePredicate` is now `typeFilter`
- `pathWithArgsPredicate` is now `pathWithArgsFilter`
- `pathPredicate` is now `pathFilter`
- `argsPredicate` is now `argsFilter`

> **Warning**
> This PR should not contain any breaking changes, tests have been added to ensure so. If there's any, it's a bug.

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🐶

### CODE REVIEW

**Comment by angeloashmore** [comment]
LGTM for the most part! 👍

> predicates params (deprecated) is now filters param

Let's remove the deprecated exports and methods from v6 as part of this major version. We can introduce new deprecations this version while removing ones from last version. Before merging, could you do a quick find-and-replace for `@deprecated` and `TODO` to find them all?

> - `HTMLFunctionSerializer` (deprecated) is now `HTMLRichTextFunctionSerializer`
> - `HTMLMapSerializer` (deprecated) is now `HTMLRichTextMapSerializer`

Unrelated to the renames, what do you think of adding an `HTMLRichTextSerializer` export? In most cases, I don't think devs need to distinguish between map and function serializers.

```ts
type HTMLRichTextSerializer = HTMLRichTextFunctionSerializer | HTMLRichTextMapSerializer
```

**Review by angeloashmore — DISMISSED** [review]
LGTM for the most part! 👍

> predicates params (deprecated) is now filters param

Let's remove the deprecated exports and methods from v6 as part of this major version. We can introduce new deprecations this version while removing ones from last version. Before merging, could you do a quick find-and-replace for `@deprecated` and `TODO` to find them all?

> - `HTMLFunctionSerializer` (deprecated) is now `HTMLRichTextFunctionSerializer`
> - `HTMLMapSerializer` (deprecated) is now `HTMLRichTextMapSerializer`

Unrelated to the renames, what do you think of adding an `HTMLRichTextSerializer` export? In most cases, I don't think devs need to distinguish between map and function serializers.

```ts
type HTMLRichTextSerializer = HTMLRichTextFunctionSerializer | HTMLRichTextMapSerializer
```

**Comment by lihbr** [comment]
> Let's remove the deprecated exports and methods from v6 as part of this major version. We can introduce new deprecations this version while removing ones from last version. Before merging, could you do a quick find-and-replace for `@deprecated` and `TODO` to find them all?

That's the case, all "deprecated" API from `@prismicio/client` v6 were removed already (outside of this PR). What's left:
- Prismic API deprecated APIs (e.g. `experiments` in the repository response, or `LegacySlices` type of slice, those are kept to stay in sync with internal types)
- "Newly" deprecated API, that is to say the API deprecated in this PR. I thought it might be less rough on users/framework SDKs to not remove the `predicate` export yet (and the `predicates` params on the client), but if you think it's better to get rid of it right away, sure thing.

> Unrelated to the renames, what do you think of adding an `HTMLRichTextSerializer` export? In most cases, I don't think devs need to distinguish between map and function serializer.

Done, added the export and made field capitalization consistent while I was at it :)

**Comment by angeloashmore** [comment]
> That's the case, all "deprecated" API from `@prismicio/client` v6 were removed already (outside of this PR). What's left:
> 
> * Prismic API deprecated APIs (e.g. `experiments` in the repository response, or `LegacySlices` type of slice, those are kept to stay in sync with internal types)
> * "Newly" deprecated API, that is to say the API deprecated in this PR. I thought it might be less rough on users/framework SDKs to not remove the `predicate` export yet (and the `predicates` params on the client), but if you think it's better to get rid of it right away, sure thing.

Perfect! Sorry, I misunderstood the previous message.

Re: `predicate`, the PR is correct; we should deprecate (but not remove) `predicate` and introduce `filter`. Although we could technically make the change now since this will be a major version, I think your intuition is correct in that it could be annoying to upgrade.

This PR looks good to merge!

**Pull request merged**
