### PR TITLE
feat: add `getGraphQLEndpoint` and `Client.prototype.graphqlFetch`

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This adds a way for a client to integrate into GraphQL libraries like Apollo, urql, and `graphql-request`.

More details: #202

## Checklist:

- [x] My change requires an update to the official documentation.
- [ ] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🦒

### CODE REVIEW

**Comment by lihbr** [comment]
Looking good to me so far! HMU when you want me to test/review ☺️

**Comment by lihbr** [comment]
Okay, not what I wanted to do ^^' Wanted to close this one and reopen one targeting master 🤔

**Comment by angeloashmore** [comment]
Merged outside this PR. The `graphqlFetch()` method is marked as `@experimental` at this time since the API may change.

This will be published along with the next bug fix or feature.

**Comment by jere-co** [comment]
Please add the usage of this to documentation as well.

**Comment by angeloashmore** [comment]
Hi @jere-co, documentation for these new features will be added. Until the docs are updated, you can see an example here: https://github.com/prismicio/prismic-client/issues/202#issue-1077360035

**Pull request closed without merging**
