### PR TITLE
Use Authorization header to send access token

### PR DESCRIPTION
**Pull request by Raph22**
Instead of using `access_token` query parameter to pass the access token, we now use the Authorization header like that:
```
Authorization: Token MY_SUPER_TOKEN
```
fixes prismicio/issue-tracker-wroom#351

### CODE REVIEW

**Comment by francois-riviere** [comment]
fixes https://github.com/prismicio/issue-tracker-wroom/issues/351

**Review by arnaudlewis — APPROVED** [review]
seems good on the code part but a test is necessary @francois-riviere

**Review by bapmrl — CHANGES_REQUESTED** [review]
Please do not merge as is because the CORS preflight request fails. See this [comment](https://github.com/prismicio/issue-tracker-wroom/issues/351#issuecomment-812010428).

**Comment by lihbr** [comment]
Related: https://github.com/prismicio/prismic-javascript/issues/168

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6

**Pull request closed without merging**
